# Welcome to Jekyll!


# In addition to these settings, there is a file _data/tokens-template.yml
# that you'll want to customize for your site. It's named 'tokens' because
# that was it's original purpose, but because tokens.yml is .gitexcluded, it's
# a good place to store your site-specific data that you'd rather not have
# forked or cloned. Of course, that means you'd want to back it up elsewhere.

# Also, for your post bylines, add author info for yourself in `_data/authors.yml`.
# (Using that method instead of site.owner, in case your posts get cloned with your repo.)

# Site settings
title: Dr.C. Naveen Kumar
description: Flowing creativity &#x2192; Cascading bliss
owner:
  name: Dr. C. Naveen Kumar # or company name
  email: doccnk@gmail.com
  url: http://www.drcnk.com
first_published: 2017 # if migrating another site, the year of your first publish
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.drcnk.com" # the base hostname & protocol for your site

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  title: Welcome!  
  text: I hope you enjoy my Research / Projects / Apps
# - title for your blog's featured posts
features-title: Featured topics
# - displayed at the bottom
closing-head: Thanks for visiting
closing-para: Feel free to get in touch. Cheers!

# on all pages (and the first three you list display with greeting, if included)
social:
  google scholar: https://scholar.google.com/citations?user=7J55iMgAAAAJ&hl=tl
  linkedin-square: https://www.linkedin.com/in/dr-c-naveen-kumar-36a1a87a/
  google-plus-square: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  twitter: https://twitter.com/cnaveenkh
  github: https://github.com/DrCNK
  #facebook-official: https://facebook.com/cnk
  youtube-square: https://www.youtube.com/@dr.c.naveenkumar8558
  email: doccnk@gmail.com
  #flickr:
  #instagram:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  stubleupon: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  delicious: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  pied-piper: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  digg: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  soundcloud: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  deviantart: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  angellist: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  tumblr-square: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  #stackexchange:
  weibo: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  trello: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  foursquare: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  linux: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  bitbucket-square: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  vk: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  slack: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  vine: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  weixin: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  yelp: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  skyatlas: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  leanpub: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  connectdevelop: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  ils: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  forumbee: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  tripadvisor: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar
  amazon: https://play.google.com/store/apps/developer?id=Dr.+C.+Naveen+Kumar

# if you use this repo's `ruby compose.rb` script to initiate new posts, put the
# command to invoke your editor here. (I didn't spend time dealing with spaces
# and full paths of the various OSes in compose.rb. For my Windows
# environment, I just put a subl.cmd file in my PATH that points to the full
# path to Sublime's subl.exe.) Also, put your most common post extension.
compose:
  editor: subl
  extension: md

# choose where to put back and next links:
# top, bottom, both, none
navlinks: bottom

# expecting more works? mark your list as in-progress
works_in_progress: yes

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed
exclude: ['site.bat','compose.rb','README.md']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # dunna work. See github.com/jekyll/jekyll/issues/2280
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post

# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []
